### ISSUE TITLE
Update code for "Block WebRTC"

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/StealthMode#10]
It is a bit outdated, the objects are still reachable from frames. We'd better update Chrome properties to block this leak like it's done here:
https://chrome.google.com/webstore/detail/webrtc-leak-prevent/eiadekoaikejlgdbkbdfeijglgfdalml?hl=en-US

**Comment by undeleted-xp** [comment]
Yes they should cope up with Google's recent updates to Chrome

**Comment by Mizzick** [comment]
Fixed
