### ISSUE TITLE
Check if it's possible to turn "disable-reading-from-canvas" from extension

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/StealthMode#11]

**Comment by undeleted-xp** [comment]
tried this command line and somehow it works but breaks chrome extension like uBlock and this Stealth Mode, I don't know others if it causes some issues. Those two extensions mentioned are the one's I notice to have issues doing this commands.

**Comment by Mizzick** [comment]
Just tried it latest Chrome 51 and it seems like this 'disable-reading-from-canvas' flag doesn't exist anymore.
I can't find it in chrome://flags/ and running Chrome from console with --disable-reading-from-canvas have no effect according to [this test site](http://www.browserleaks.com/canvas).
