### ISSUE TITLE
Referrer Spoof

### ISSUE THREAD

**Issue by Gridlocked** [AdguardTeam/StealthMode#13]
I prefer to have my referrer set to show the website I am going to through another extension.  

However Stealth continues setting the referrer to https://adguard.com/referrer.html, even when that setting is off, causing a conflict.

**Comment by ameshkov** [comment]
Hi! Can't confirm it, when "Hide my Referrer" option is turned off, stealth mode does not change it.

**Comment by Gridlocked** [comment]
Its gotta be a conflict with one of my other extensions

**Comment by ameshkov** [comment]
@Gridlocked sorry for the delay, could you please list extensions you use?

**Comment by Gridlocked** [comment]
I suspect it was a conflict with uMatrix but this has stopped on its own.  Either an update to Chrome resolved it or another extension updated and resolved it.

**Comment by ameshkov** [comment]
@Gridlocked great thank you for the information.
