### ISSUE TITLE
Password managers are being blocked

### ISSUE THREAD

**Issue by Bushido1** [AdguardTeam/StealthMode#20]
![image](https://user-images.githubusercontent.com/11409601/36905937-4cce4f1e-1e3d-11e8-8faf-994301482a18.png)
![image](https://user-images.githubusercontent.com/11409601/36905977-5fab6554-1e3d-11e8-8b0a-2de9ecea2e95.png)
![image](https://user-images.githubusercontent.com/11409601/36906021-7d73ce3c-1e3d-11e8-8cca-49a192e62181.png)
![image](https://user-images.githubusercontent.com/11409601/36906037-8bea5814-1e3d-11e8-9259-db76b55f3b6c.png)
![image](https://user-images.githubusercontent.com/11409601/36906067-a0b7344c-1e3d-11e8-8a4c-e26cd0dd9d73.png)
Personally, I have problems with making changes in the vault of bitwarden.

**Comment by Alex-302** [comment]
please paste links as text

**Comment by BooBerry** [comment]
IMO, all password managers should be added to the HTTPS exclusions list like lastpass.com is.

Some URLs to the well-known password managers (off the top of my head):

bitwarden.com
1password.com
roboform.com
enpass.io
dashlane.com

**Comment by ameshkov** [comment]
@Alex-302 at least for now we should exclude `@@||api.bitwarden.com^$stealth`

**Comment by ameshkov** [comment]
Regarding HTTPS exclusions:
https://github.com/AdguardTeam/HttpsExclusions/commit/e16e82314322e5ed70d6b849adf0304885e92d32

**Comment by BooBerry** [comment]
A couple more password manager URLs;

keepersecurity.com
zoho.com/vault
stickypassword.com

**Comment by ameshkov** [comment]
Tbh, I'd prefer to add their API urls, websites are full of tracking

**Comment by BooBerry** [comment]
I suppose that makes sense, but it might be worth mentioning that part (sites full of tracking) if any users ask why the full domain isn't excluded versus the API URL(s).

**Comment by Bushido1** [comment]
Should I update the filters and the problem is gone for bitwarden?

**Comment by ameshkov** [comment]
> I must add the rule "@@||api.bitwarden.com^$stealth" manually to user filters

Could you please check if it helps?

@Alex-302 was trying to reproduce the issue, but it works okay on his end

**Comment by Bushido1** [comment]
@ameshkov This forementioned rule fixed the problem for me.

**Comment by ameshkov** [comment]
@Alex-302 let's add it to the English filter then

**Comment by Alex-302** [comment]
done
