### ISSUE TITLE
Do-Not-Track header

### ISSUE THREAD

**Issue by specter78** [AdguardTeam/StealthMode#24]
Recent reports indicate that do-not-track header is used to identify and track users. So browsers like Chrome and Safari have removed this feature. Adguard should do the same.

**Comment by Bluscream** [comment]
No

**Comment by specter78** [comment]
May I know the reason behind your argument?

**Comment by Bluscream** [comment]
It is already optional and not enabled by default, some people might still prefer to have the option.

**Comment by ameshkov** [comment]
> Recent reports indicate that do-not-track header is used to identify and track users. So browsers like Chrome and Safari have removed this feature. Adguard should do the same.

Could you please link these reports?

**Comment by specter78** [comment]
> Could you please link these reports?

I am not able to find the exact article but it was somewhat like this -- Websites do not have to mandatorily comply with DNT request. Moreover, only small percentage of browsers have DNT enabled. This allows an additional parameter which can be used to fingerprint browsers/users, and thereby accurately identify and track them.

- [https://amiunique.org/faq](https://amiunique.org/faq) mentions list of fingerprint variables.

- [https://developer.apple.com/documentation/safari_release_notes/safari_12_1_release_notes](https://developer.apple.com/documentation/safari_release_notes/safari_12_1_release_notes) says "Removed support for the expired Do Not Track standard to prevent potential use as a fingerprinting variable.”

- [https://spreadprivacy.com/do-not-track/](https://spreadprivacy.com/do-not-track/) provides statistics about DNT.

**Comment by ameshkov** [comment]
Here's how I see it.

On one hand, DNT is obviously outdated and can be used as a part of the browser fingerprint (but don't overestimate it, 24% of users is a lot).

On the other hand, some websites do respect it, and EFF is pushing the updated DNT standard - https://www.eff.org/issues/do-not-track.

What for Apple's move, I suppose they decided that since they now have IPT enabled by default, it's not more necessary to support the outdated standard. They now should either enable DNT by default or get rid of it completely. I can see the logic here.

Adding DNT header to Safari requests in these circumstances makes little sense. In fact, it will only hurt users privacy as there is no way the user could enable it manually.

I am not so sure about other browsers, though.

**Comment by specter78** [comment]
Your argument does seem valid. However, it overlooks key concerns.

The companies which are most invasive (without naming anyone!) are also the ones who choose to ignore DNT. So, considering 25% of users with DNT enabled, it allows them two sets of database - one with 25% users and other with remaining 75%. Even if nothing else, this would increase the probability of uniquely identifying browsers.

Extending this argument further - it is better to stay in 75% non-DNT users than staying in 25% DNT ones.

**Comment by ameshkov** [comment]
To solve this issue we might start using the DNT spec proposed by eff instead of the old one:
https://www.eff.org/dnt-policy

The difference is that the DNT header will be set only if the domain explicitly opts in by posting the DNT policy file: https://www.eff.org/dnt-policy

**Comment by specter78** [comment]
I think it too, **may**, suffer from the same issue. Although we’ll have to wait and see.

> We believe it would be a false and misleading trade practice to post the policy without the intent to comply in good faith. However, EFF is not in a position to enforce this promise or monitor compliance. [(https://www.eff.org/dnt-policy)](https://www.eff.org/dnt-policy)

**Comment by ameshkov** [comment]
Moved to the proper repos:

* https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1391
* https://github.com/AdguardTeam/CoreLibs/issues/887

Thank you for the discussion!
