### ISSUE TITLE
hide referrer from third parties issue

### ISSUE THREAD

**Issue by undeleted-xp** [AdguardTeam/StealthMode#6]
When enabled I can't access videos streams (embedded videos) at http://putlocker.is/. I'm using Stealthmode Google chrome extension. Please fix this problem. Thanks

**Comment by ameshkov** [comment]
@Alex-302 please take a look

**Comment by Alex-302** [comment]
@undeleted-xp 
Please check this rule in user filter:
```
@@||thevideos.tv/embed-$stealth
```

**Comment by ameshkov** [comment]
@Alex-302 $stealth is not supported in Stealth Mode extension.
Just add it to the spyware filter

**Comment by undeleted-xp** [comment]
Just found out that it breaks imdb site also when enabled.

**Comment by undeleted-xp** [comment]
If I put those site on whitelist of Stealtmode will that affect (disable) the **Tracking Methods** and **Miscellaneous** option or just the **Filters**?

**Comment by ameshkov** [comment]
Yep, this will turn off everything for these websites

**Comment by Alex-302** [comment]
@ameshkov 
>$stealth is not supported in Stealth Mode extension.
Just add it to the spyware filter

without $stealth ? Ads will be unblocked, Or what?

**Comment by undeleted-xp** [comment]
are there any fix to this aside from whitelisting and turning of referrer option.

**Comment by ameshkov** [comment]
> are there any fix to this aside from whitelisting and turning of referrer option.

To fix it for good we should update the stealth mode extension code and add support for $stealth filter modifier (so we can update filters on the server side).

So, temporary solution: whitelist and wait for the next version of the stealth mode extension.

**Comment by undeleted-xp** [comment]
Thanks maybe I'll just wait for fix. Whitelisting disables everything, so for the time being turning off referrer option temporarily would be an option until a solution arrives.

**Comment by Alex-302** [comment]
Added to English filter:
`@@||thevideos.tv/embed-$stealth`

**Comment by Mizzick** [comment]
Fixed with #7
